In [2]:
import numpy as np

In [10]:
a = np.ones((5,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [14]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 7
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 7. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 7. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# Reorganizing Arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)

print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Load data from a text file

In [3]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [4]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [22]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [6]:
a = np.array([1,3,4,6,7,8,9])
a[ [1,2,5] ]

array([3, 4, 8])

In [23]:
np.any(filedata>50, 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [24]:
np.all(filedata>50, 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

##### Boolean Masking and Advanced Indexing

In [25]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [27]:
array = np.arange(1, 31).reshape(6, 5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [29]:
array[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [30]:
array[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [31]:
array[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [32]:
weight_lb = np.array([125, 98, 135, 170, 162, 147, 144, 177, 180, 112])
np_weight_kg = weight_lb * 0.453592

np_height_m = np.array([1.77, 1.45, 1.85, 2.2, 1.75, 1.66, 1.70, 1.89, 2.1, 1.6])

BMI = np_weight_kg / np_height_m ** 2
print(BMI)

light = BMI < 21
print(light)

print(BMI[light])
print(np.mean(np_height_m))
print(np.median(np_height_m))

[18.09792844 21.14245707 17.89186852 15.93195041 23.9940911  24.19727972
 22.60112388 22.47579407 18.51395918 19.84465   ]
[ True False  True  True False False False False  True  True]
[18.09792844 17.89186852 15.93195041 18.51395918 19.84465   ]
1.7970000000000002
1.76


### Q1: Convert the follwoing first array into the second array
```python
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
```


### Q2: Convert the follwoing first array into the second array
```python
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])
```

### Q3: Convert the follwoing first array into the second array
```python
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 7. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
```

### Q4: Convert the follwoing first array into the second array
```python
[[1 2 3 4]
 [5 6 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
```

### Q5: Combine the follwoing first two arrays to produce the third array
```python
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0.]
 [0. 0.]]

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])
```

### Q6: Load the data from "data.txt" file and extract the following array from there

```python 
array([196,  75, 766,  75,  55, 999,  78,  76,  88])
```

### Q7: Load the data from "data.txt" file and extract the following two information arrays

```python
array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])
```

### Q8: Load the data from "data.txt" file and extract the following array from there (Hint: min=50, max=100)

```python 
array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])
```

### Q9: Index the marked parts of the following matrix in three seperate arrays:

![image.png](attachment:image.png)

>Output:
```python 
array([[11, 12],
       [16, 17]])

array([ 2,  8, 14, 20])

array([[ 4,  5],
       [24, 25],
       [29, 30]])
```

### 10: Create a numpy array and name it `weight_lb` (Give acceptable weight values for 10 humans)
- Multiply  by 0.453592 to go from pounds to kilograms and store the resulting numpy array as np_weight_kg
- Create np_height_m numpy array and store acceptable height values for 10 humans
- Calculate the BMI for each player using this equation:
    - BMI = weight(kg)/height(m) ** 2
- Save the resulting numpy array as BMI
- Print out BMI
- Create a boolean numpy array
    - The element of the array should be True if the corresponding baseball player's BMI is below 21
    - Name the array ***light*** and print it
- Print out a Numpy array with the BMIs of all baseball players whose BMI is below 21
- Print the mean of np_height_m
- Print the median of np_height_m