### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array( [1,2,3], dtype='int32')
print(a)

[1 2 3]


In [14]:
b = np.array([ [9.0,8.0,7.0], [6.0,5.0,4.0] ])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
a.shape

(3,)

In [7]:
# Get Type
a.dtype

dtype('int32')

In [8]:
# Get Size
a.itemsize

4

In [9]:
# Get total size
a.nbytes

12

In [10]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [13]:
a = np.array([ [1,2,3,4,5,6,7] ,[8,9,10,11,12,13,14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specific element [r, c]
a[1, 5]

13

In [15]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [17]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [18]:
print(a)
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [19]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [20]:
b = np.array([ [ [1,2],[3,4] ] ,[ [5,6], [7,8] ] ])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
b.shape

(2, 2, 2)

In [22]:
# Get specific element (work outside in)
b[0,1,1]

4

In [23]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [15]:
# All 0s matrix
np.zeros( (5,5) ) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [19]:
# Any other number
np.full((5,5), 99)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [27]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [28]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.31307356, 0.40040449],
       [0.75539891, 0.1065656 ],
       [0.39833566, 0.64220308],
       [0.76641074, 0.42529612]])

In [30]:
# Random Integer values
np.random.randint(-4,8, size=(4,3))

array([[-1,  3,  7],
       [ 6,  6,  4],
       [-4, -2,  5],
       [-1,  2,  7]])

In [31]:
# The identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
# Repeat an array
arr = np.array([[1,2,3]])
print(arr)
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


##### Be careful when copying arrays!!!

In [21]:
a = np.array([1,2,3])
b = a
print(b)
b[0] = 100
print(b)

[1 2 3]
[100   2   3]


In [22]:
print(a)

[100   2   3]


### Mathematics

In [38]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [39]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
a ** 2

In [ ]:
# Take the sin
np.cos(a)



In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [40]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)



[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [41]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats)

In [ ]:
np.max(stats, axis=1)

In [ ]:
np.sum(stats, axis=0)

### Reorganizing Arrays

In [42]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)



[[1 2 3 4]
 [5 6 7 8]]


In [46]:
print(before>7)

[[False False False False]
 [False False False  True]]


In [43]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])